# -----------------------
# Changelog Configuration
# -----------------------
changeLogFile=postgres_changelog/postgresdb.changelog.sql

# -----------------------
# Schema Settings
# -----------------------
defaultSchemaName=public
liquibaseSchemaName=public

# -----------------------
# Logging
# -----------------------
logLevel=info

# -----------------------
# Behavior Controls
# -----------------------
shouldRun=true

databaseChangeLogTableName=DATABASECHANGELOG
databaseChangeLogLockTableName=DATABASECHANGELOGLOCK
