# -----------------------
# Changelog Configuration
# -----------------------
changeLogFile=mssql_changelog/sqldb.changelog.sql

# -----------------------
# Schema Settings
# -----------------------
defaultSchemaName=${MSSQL_DB_SCHEMA}
liquibaseSchemaName=${MSSQL_DB_SCHEMA}

# -----------------------
# Behavior Controls
# -----------------------
shouldRun=true
databaseChangeLogTableName=DATABASECHANGELOG
databaseChangeLogLockTableName=DATABASECHANGELOGLOCK

# -----------------------
# Logging
# -----------------------
logLevel=info
