# -----------------------
# Changelog Configuration
# -----------------------
changeLogFile=mssql_changelog/sqldb.changelog.sql

# -----------------------
# Schema Settings
# -----------------------
defaultSchemaName=dbo_dev
liquibaseSchemaName=dbo_dev

# -----------------------
# Behavior Controls
# -----------------------
shouldRun=true
databaseChangeLogTableName=DATABASECHANGELOG
databaseChangeLogLockTableName=DATABASECHANGELOGLOCK

# -----------------------
# Logging
# -----------------------
logLevel=info
