name: SQL Server Database Deployment (Liquibase CD)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    runs-on: [self-hosted]

    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Generate "rollback" tag
        id: generate-rollback-tag
        shell: bash 
        run: |
          timestamp=$(date -u +"%Y%m%d%H%M%S")
          uuid_tmp=$(uuidgen | tr '[:upper:]' '[:lower:]')
          rollback_tag="rb-${{ inputs.environment }}-${timestamp}-${uuid_tmp}"
          echo "rollback_tag=${rollback_tag}" >> $GITHUB_OUTPUT
    
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Managed Identity Credentials
        run: |
          MSSQL_PWD=$(curl -s "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fossrdbms-aad.database.windows.net" -H Metadata:true | jq -r .access_token)
          echo "::add-mask::$MSSQL_PWD"
          # echo "LIQUIBASE_COMMAND_PASSWORD=$MSSQL_PWD" >> "$GITHUB_ENV"

      - name: Auto populate database connection parameters
        id: get-credentials
        run: |
          ENV_NAME_UPPER=$(echo "${{ github.event.inputs.environment }}" | tr '[:lower:]' '[:upper:]')
          
          case "$ENV_NAME_UPPER" in
            DEV)
              echo "db_host=${{ secrets.MSSQL_DEV_DB_HOST }}" >> $GITHUB_OUTPUT
              echo "db_name=${{ secrets.MSSQL_DEV_DB_NAME }}" >> $GITHUB_OUTPUT
              echo "db_user=${{ secrets.MSSQL_DEV_DB_USER }}" >> $GITHUB_OUTPUT
              # echo "db_pass=${{ secrets.MSSQL_DEV_DB_PASSWORD }}" >> $GITHUB_OUTPUT
              echo "mssql_db_schema=dbo_dev" >> $GITHUB_OUTPUT
              ;;
            QA)
              echo "db_host=${{ secrets.MSSQL_QA_DB_HOST }}" >> $GITHUB_OUTPUT
              echo "db_name=${{ secrets.MSSQL_QA_DB_NAME }}" >> $GITHUB_OUTPUT
              echo "db_user=${{ secrets.MSSQL_QA_DB_USER }}" >> $GITHUB_OUTPUT
              # echo "db_pass=${{ secrets.MSSQL_QA_DB_PASSWORD }}" >> $GITHUB_OUTPUT
              echo "mssql_db_schema=dbo_qa" >> $GITHUB_OUTPUT
              ;;
            PROD)
              echo "db_host=${{ secrets.MSSQL_PROD_DB_HOST }}" >> $GITHUB_OUTPUT
              echo "db_name=${{ secrets.MSSQL_PROD_DB_NAME }}" >> $GITHUB_OUTPUT
              echo "db_user=${{ secrets.MSSQL_PROD_DB_USER }}" >> $GITHUB_OUTPUT
              # echo "db_pass=${{ secrets.MSSQL_PROD_DB_PASSWORD }}" >> $GITHUB_OUTPUT
              echo "mssql_db_schema=dbo_prod" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Debug schema 
        run: | 
          echo "MSSQL_DB_SCHEMA=${MSSQL_DB_SCHEMA}" 
          echo "db_user"=${{steps.get-credentials.outputs.db_user}}
        env: 
          MSSQL_DB_SCHEMA: ${{ steps.get-credentials.outputs.mssql_db_schema }}
          
      - name: Verify Database Connection Details
        run: |
          echo "Target environment: ${{ github.event.inputs.environment }}"

      - name: Setup Liquibase
        uses: liquibase/setup-liquibase@v3
        with: 
          version: '4.33.0'
          edition: "community"

      - name: Get azure-deps directory path
        shell: bash
        run: |
          LIQUIBASE_BIN=$(readlink -f $(command -v liquibase))
          LIQUIBASE_HOME=$(dirname "${LIQUIBASE_BIN}")
          echo "LIQUIBASE_HOME=$LIQUIBASE_HOME" >> "$GITHUB_ENV"
          echo "Liquibase home: $LIQUIBASE_HOME
      
      - name: Check Liquibase Changes Log Validity (liquibase validate Command)
        run: |
          liquibase validate \
            --defaults-file=mssql.liquibase.properties \
            --default-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --liquibase-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --changelog-file=mssql_changelog/sqldb.changelog.sql \
            --url="jdbc:sqlserver://${{ steps.get-credentials.outputs.db_host }}:1433;databaseName=${{ steps.get-credentials.outputs.db_name }};authentication=ActiveDirectoryManagedIdentity;encrypt=true;trustServerCertificate=true;" \
            -Dschema_name=${{ steps.get-credentials.outputs.mssql_db_schema }}
      
      - name: Database Pre-check (liquibase validate Command)
        run: | 
          liquibase status --verbose \
            --defaults-file=mssql.liquibase.properties \
            --default-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --liquibase-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --changelog-file=mssql_changelog/sqldb.changelog.sql \
            --url="jdbc:sqlserver://${{ steps.get-credentials.outputs.db_host }}:1433;databaseName=${{ steps.get-credentials.outputs.db_name }};authentication=ActiveDirectoryManagedIdentity;encrypt=true;trustServerCertificate=true;" \
            -Dschema_name=${{ steps.get-credentials.outputs.mssql_db_schema }}


      - name: Capture Pre-deployment Schema State (liquibase snapshot Command)
        run: | 
          liquibase snapshot \
            --defaults-file=mssql.liquibase.properties \
            --default-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --liquibase-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --url="jdbc:sqlserver://${{ steps.get-credentials.outputs.db_host }}:1433;databaseName=${{ steps.get-credentials.outputs.db_name }};authentication=ActiveDirectoryManagedIdentity;encrypt=true;trustServerCertificate=true;" \
            --snapshot-format=json \
            --output-file=pre_deploy_snapshot_${{steps.get-credentials.outputs.db_name}}.json

            
      - name: Apply Database Changes (liquibase update Command)
        run: |
          liquibase update \
            --defaults-file=mssql.liquibase.properties \
            --changelog-file=mssql_changelog/sqldb.changelog.sql \
            --default-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --liquibase-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --url="jdbc:sqlserver://${{ steps.get-credentials.outputs.db_host }}:1433;databaseName=${{ steps.get-credentials.outputs.db_name }};authentication=ActiveDirectoryManagedIdentity;encrypt=true;trustServerCertificate=true;" \
            -Dschema_name=${{ steps.get-credentials.outputs.mssql_db_schema }}

      - name: Tag Database Changes (liquibase tag Command)
        run: |
          liquibase tag \
            --defaults-file=mssql.liquibase.properties \
            --default-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --liquibase-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --url="jdbc:sqlserver://${{ steps.get-credentials.outputs.db_host }}:1433;databaseName=${{ steps.get-credentials.outputs.db_name }};authentication=ActiveDirectoryManagedIdentity;encrypt=true;trustServerCertificate=true;" \
            --tag=${{ steps.generate-rollback-tag.outputs.rollback_tag }}


      - name: Capture Post-deployment Schema State (liquibase snapshot Command)
        run: |
          liquibase snapshot \
            --defaults-file=mssql.liquibase.properties \
            --default-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --liquibase-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --url="jdbc:sqlserver://${{ steps.get-credentials.outputs.db_host }}:1433;databaseName=${{ steps.get-credentials.outputs.db_name }};authentication=ActiveDirectoryManagedIdentity;encrypt=true;trustServerCertificate=true;" \
            --snapshot-format=json \
            --output-file=post_deploy_snapshot_${{steps.get-credentials.outputs.db_name}}.json


      - name: Check Database Schema Difference Before & After Deployment (liquibase diff Command)
        run: |
          liquibase diff \
            --defaults-file=mssql.liquibase.properties \
            --default-schema-name="${{ steps.get-credentials.outputs.mssql_db_schema }}" \
            --reference-url="offline:mssql?snapshot=pre_deploy_snapshot_${{steps.get-credentials.outputs.db_name}}.json" \
            --url="jdbc:sqlserver://${{ steps.get-credentials.outputs.db_host }}:1433;databaseName=${{ steps.get-credentials.outputs.db_name }};authentication=ActiveDirectoryManagedIdentity;encrypt=true;trustServerCertificate=true;"
