name: PostgreSQL Database Schema Drift (Liquibase CI)

on:
  workflow_dispatch:
    inputs:
      environment_src:
        description: "Baseline environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod
      
      environment_tgt:
        description: "Comparing environment"
        required: true
        default: "qa"
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Managed Identity Credentials
        run: |
          PG_PWD=$(curl -s "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fossrdbms-aad.database.windows.net" -H Metadata:true | jq -r .access_token)
          echo "::add-mask::$PG_PWD"
          echo "LIQUIBASE_COMMAND_PASSWORD=$PG_PWD" >> "$GITHUB_ENV"

      - name: Auto populate database connection parameters
        id: get-host-dbname
        run: |
          SRC_ENV_NAME_UPPER=$(echo "${{ github.event.inputs.environment_src }}" | tr '[:lower:]' '[:upper:]')
          
          case "$SRC_ENV_NAME_UPPER" in
            DEV)
              echo "src_db_host=${{ secrets.DEV_DB_HOST }}" >> $GITHUB_OUTPUT
              echo "src_db_name=${{ secrets.DEV_DB_NAME }}" >> $GITHUB_OUTPUT
              echo "src_db_user=${{ secrets.DEV_DB_USER }}" >> $GITHUB_OUTPUT
              ;;
            QA)
              echo "src_db_host=${{ secrets.QA_DB_HOST }}" >> $GITHUB_OUTPUT
              echo "src_db_name=${{ secrets.QA_DB_NAME }}" >> $GITHUB_OUTPUT
              echo "src_db_user=${{ secrets.QA_DB_USER }}" >> $GITHUB_OUTPUT
              ;;
            PROD)
              echo "src_db_host=${{ secrets.PROD_DB_HOST }}" >> $GITHUB_OUTPUT
              echo "src_db_name=${{ secrets.PROD_DB_NAME }}" >> $GITHUB_OUTPUT
              echo "src_db_user=${{ secrets.PROD_DB_USER }}" >> $GITHUB_OUTPUT
              ;;
          esac

          TGT_ENV_NAME_UPPER=$(echo "${{ github.event.inputs.environment_tgt }}" | tr '[:lower:]' '[:upper:]')
          
          case "$TGT_ENV_NAME_UPPER" in
            DEV)
              echo "tgt_db_host=${{ secrets.DEV_DB_HOST }}" >> $GITHUB_OUTPUT
              echo "tgt_db_name=${{ secrets.DEV_DB_NAME }}" >> $GITHUB_OUTPUT
              echo "tgt_db_user=${{ secrets.DEV_DB_USER }}" >> $GITHUB_OUTPUT
              ;;
            QA)
              echo "tgt_db_host=${{ secrets.QA_DB_HOST }}" >> $GITHUB_OUTPUT
              echo "tgt_db_name=${{ secrets.QA_DB_NAME }}" >> $GITHUB_OUTPUT
              echo "tgt_db_user=${{ secrets.QA_DB_USER }}" >> $GITHUB_OUTPUT
              ;;
            PROD)
              echo "tgt_db_host=${{ secrets.PROD_DB_HOST }}" >> $GITHUB_OUTPUT
              echo "tgt_db_name=${{ secrets.PROD_DB_NAME }}" >> $GITHUB_OUTPUT
              echo "tgt_db_user=${{ secrets.PROD_DB_USER }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Setup Liquibase
        uses: liquibase/setup-liquibase@v3
        with: 
          version: '4.33.0'
          edition: "community"
      
      - name: Source Database Pre-check (liquibase validate Command)
        run: | 
          liquibase status --verbose \
            --changelog-file=postgres_changelog/postgresdb.changelog.sql \
            --url="jdbc:postgresql://${{ steps.get-host-dbname.outputs.src_db_host }}:5432/${{ steps.get-host-dbname.outputs.src_db_name }}?sslmode=require" \
            --username="${{ steps.get-host-dbname.outputs.src_db_user }}"
            
      - name: Target Database Pre-check (liquibase validate Command)
        run: | 
          liquibase status --verbose \
            --changelog-file=postgres_changelog/postgresdb.changelog.sql \
            --url="jdbc:postgresql://${{ steps.get-host-dbname.outputs.tgt_db_host }}:5432/${{ steps.get-host-dbname.outputs.tgt_db_name }}?sslmode=require" \
            --username="${{ steps.get-host-dbname.outputs.tgt_db_user }}"
        
      - name: Check Database Schema Difference (liquibase diff Command)
        run: |
          liquibase diff \
            --url="jdbc:postgresql://${{ steps.get-host-dbname.outputs.src_db_host }}:5432/${{ steps.get-host-dbname.outputs.src_db_name }}?sslmode=require" \
            --username="${{ steps.get-host-dbname.outputs.src_db_user }}" \
            --reference-url="jdbc:postgresql://${{ steps.get-host-dbname.outputs.tgt_db_host }}:5432/${{ steps.get-host-dbname.outputs.tgt_db_name }}?sslmode=require" \
            --reference-username="${{ steps.get-host-dbname.outputs.tgt_db_user }}"

